-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ores_classification (
  oresc_id BIGSERIAL NOT NULL,
  oresc_rev INT NOT NULL,
  oresc_model SMALLINT NOT NULL,
  oresc_class SMALLINT NOT NULL,
  oresc_probability NUMERIC(3, 3) NOT NULL,
  oresc_is_predicted SMALLINT NOT NULL,
  PRIMARY KEY(oresc_id)
);

CREATE UNIQUE INDEX oresc_rev_model_class ON ores_classification (
  oresc_rev, oresc_model, oresc_class
);

CREATE INDEX oresc_model_class_prob ON ores_classification (
  oresc_model, oresc_class, oresc_probability
);


CREATE TABLE ores_model (
  oresm_id SMALLSERIAL NOT NULL,
  oresm_name VARCHAR(32) NOT NULL,
  oresm_version VARCHAR(32) NOT NULL,
  oresm_is_current SMALLINT NOT NULL,
  PRIMARY KEY(oresm_id)
);

CREATE INDEX oresm_model_status ON ores_model (oresm_name, oresm_is_current);

CREATE UNIQUE INDEX oresm_version ON ores_model (oresm_name, oresm_version);
