-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ores_classification (
  oresc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  oresc_rev INTEGER UNSIGNED NOT NULL,
  oresc_model SMALLINT NOT NULL,
  oresc_class SMALLINT NOT NULL,
  oresc_probability NUMERIC(3, 3) NOT NULL,
  oresc_is_predicted SMALLINT NOT NULL
);

CREATE UNIQUE INDEX oresc_rev_model_class ON /*_*/ores_classification (
  oresc_rev, oresc_model, oresc_class
);

CREATE INDEX oresc_model_class_prob ON /*_*/ores_classification (
  oresc_model, oresc_class, oresc_probability
);


CREATE TABLE /*_*/ores_model (
  oresm_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  oresm_name VARCHAR(32) NOT NULL,
  oresm_version VARCHAR(32) NOT NULL,
  oresm_is_current SMALLINT NOT NULL
);

CREATE INDEX oresm_model_status ON /*_*/ores_model (oresm_name, oresm_is_current);

CREATE UNIQUE INDEX oresm_version ON /*_*/ores_model (oresm_name, oresm_version);
