-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ores_classification (
  oresc_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  oresc_rev INT UNSIGNED NOT NULL,
  oresc_model SMALLINT NOT NULL,
  oresc_class TINYINT NOT NULL,
  oresc_probability NUMERIC(3, 3) NOT NULL,
  oresc_is_predicted TINYINT(1) NOT NULL,
  UNIQUE INDEX oresc_rev_model_class (
    oresc_rev, oresc_model, oresc_class
  ),
  INDEX oresc_model_class_prob (
    oresc_model, oresc_class, oresc_probability
  ),
  PRIMARY KEY(oresc_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ores_model (
  oresm_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  oresm_name VARCHAR(32) NOT NULL,
  oresm_version VARCHAR(32) NOT NULL,
  oresm_is_current TINYINT(1) NOT NULL,
  INDEX oresm_model_status (oresm_name, oresm_is_current),
  UNIQUE INDEX oresm_version (oresm_name, oresm_version),
  PRIMARY KEY(oresm_id)
) /*$wgDBTableOptions*/;
